apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-tm-key-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node1-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"Wl+xSyXVuuqzpvznOS7dOobhcn4C5auxkFRi7yLtgtA="},"type":"unlocked"}
  tm.pub: |-
    BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-nodekey-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node1-nodekey-config
data:
  nodekey: |
    1be3b50b31734be48452c29d714941ba165ef0cbf3ccea8ca16c45e3d8d45fb0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-enode-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node1-enode-config
data:
  enode: |
    ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-account-key-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node1-account-key-config
data:
  key: |-
    {"address":"ed9d02e382b34818e88b88a309c7fe71e65f419d","crypto":{"cipher":"aes-128-ctr","ciphertext":"4e77046ba3f699e744acb4a89c36a3ea1158a1bd90a076d36675f4c883864377","cipherparams":{"iv":"a8932af2a3c0225ee8e872bc0e462c11"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"8ca49552b3e92f79c51f2cd3d38dfc723412c212e702bd337a3724e8937aff0f"},"mac":"6d1354fef5aa0418389b1a5d1f5ee0050d7273292a1171c51fd02f9ecff55264"},"id":"a65d1ac3-db7e-445d-a1cc-b6c5eeaa05e0","version":3}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-tm-key-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node2-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"nDFwJNHSiT1gNzKBy9WJvMhmYRkW3TzFUmPsNzR6oFk="},"type":"unlocked"}
  tm.pub: |-
    QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-nodekey-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node2-nodekey-config
data:
  nodekey: |
    9bdd6a2e7cc1ca4a4019029df3834d2633ea6e14034d6dcc3b944396fe13a08b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-enode-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node2-enode-config
data:
  enode: |
    0ba6b9f606a43a95edc6247cdb1c1e105145817be7bcafd6b2c0ba15d58145f0dc1a194f70ba73cd6f4cdd6864edc7687f311254c7555cc32e4d45aeb1b80416
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-account-key-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node2-account-key-config
data:
  key: |-
    {"address":"ca843569e3427144cead5e4d5999a3d0ccf92b8e","crypto":{"cipher":"aes-128-ctr","ciphertext":"01d409941ce57b83a18597058033657182ffb10ae15d7d0906b8a8c04c8d1e3a","cipherparams":{"iv":"0bfb6eadbe0ab7ffaac7e1be285fb4e5"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"7b90f455a95942c7c682e0ef080afc2b494ef71e749ba5b384700ecbe6f4a1bf"},"mac":"4cc851f9349972f851d03d75a96383a37557f7c0055763c673e922de55e9e307"},"id":"354e3b35-1fed-407d-a358-889a29111211","version":3}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-tm-key-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node3-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"tMxUVR8bX7aq/TbpVHc2QV3SN2iUuExBwefAuFsO0Lg="},"type":"unlocked"}
  tm.pub: |-
    1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-nodekey-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node3-nodekey-config
data:
  nodekey: |
    722f11686b2277dcbd72713d8a3c81c666b585c337d47f503c3c1f3c17cf001d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-enode-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node3-enode-config
data:
  enode: |
    579f786d4e2830bbcc02815a27e8a9bacccc9605df4dc6f20bcc1a6eb391e7225fff7cb83e5b4ecd1f3a94d8b733803f2f66b7e871961e7b029e22c155c3a778
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-account-key-config
  namespace: quorum-test
  labels:
    app: qubernetes
    name: quorum-node3-account-key-config
data:
  key: |-
    {"address":"0fbdc686b912d7722dc86510934589e0aaf3b55a","crypto":{"cipher":"aes-128-ctr","ciphertext":"6b2c72c6793f3da8185e36536e02f574805e41c18f551f24b58346ef4ecf3640","cipherparams":{"iv":"582f27a739f39580410faa108d5cc59f"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"1a79b0db3f8cb5c2ae4fa6ccb2b5917ce446bd5e42c8d61faeee512b97b4ad4a"},"mac":"cecb44d2797d6946805d5d744ff803805477195fab1d2209eddc3d1158f2e403"},"id":"f7292e90-af71-49af-a5b3-40e8493f4681","version":3}